### ISSUE TITLE
Hello from GenniaApp

### ISSUE THREAD

**Issue by Reqwey** [fluffybeastgames/MadJS#17]
Your MadJS is a really wonderful project. 
We are now building a game like this too.
* [Gennia](https://github.com/GenniaApp/Gennia): An offline Electron app
* [GenniaServer](https://github.com/GenniaApp/GenniaServer): A web-based one.
It is currently running on https://gennia.io

Would you like to join our team @GenniaApp to help us?

**Comment by fluffybeastgames** [comment]
Hi @Reqwey! @Jackiexiao showed me your project and it's really impressive! I would love to contribute to it if I can! It's very cool to see how projects with similar goals can unfold in really different ways.
